### PR TITLE
Develop 陳易 Week-01 Assignment

### PR DESCRIPTION
**Pull request by Twilight0915**
http://18.180.213.40:3000/api/attractions?page=1
http://18.180.213.40:3000/api/attractions?page=0&keyword=藝文館所
http://18.180.213.40:3000/api/attractions?page=0&keyword=北
http://18.180.213.40:3000/api/attraction/10

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. There should have some data in http://18.180.213.40:3000/api/attractions?page=1
2. `images` field of attraction should be a string array where every image URL of attraction should be a element in this array. For example: `["Image URL 1", "Image URL 2", ...]`

**Comment by Twilight0915** [comment]
Modified  keyword error and images style error

**Comment by cwpeng** [comment]
Re-request review from reviewers section in the right side of this page, so that I can review for you.

**Comment by Twilight0915** [comment]
Sorry, it's my fault.  I have finished.

**Review by cwpeng — COMMENTED** [review]
But your live URLs are borken.

**Comment by Twilight0915** [comment]
I use connection pool to solve this error.

**Review by cwpeng — CHANGES_REQUESTED** [review]
Result is OK, but
1. We nerver use SQL like this `SELECT * FROM data`. It's much better to use `LIMIT` in SQL to do pagination than get ALL DATA and do it in your own code.
2. We should use second parameter of execute method to apply variable data into SQL query.

**Comment by Twilight0915** [comment]
I have done with using Limit in SQL to do pagination.

**Review by cwpeng — CHANGES_REQUESTED** [review]
We should use second parameter of execute method to apply variable data into SQL query.

**Comment by Twilight0915** [comment]
I havd done with using second parameter of execute method.

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
